a=open('D:\python\pythonsamples\day6\sampfile.txt','a')
a.write("hai\n")
a.write('hello\n')
a.write('welcome\n')
a.write('to\n')
a.write('digilync\n')

a.seek(5)
a.write('aaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n')
a.close()